### ISSUE TITLE
Causing some video with no sound

### ISSUE THREAD

**Issue by Paramirage** [niklas-englert/9GAG-Controls#8]
It is causing some video on 9gag with no sound when I toggle auto unmute on and off. for example https://9gag.com/gag/aL1yNBM
I am using latest firefox build and no issue on the video side in chrome or other browser. Video got audio back after disabling addon. Please fix it.

**Comment by niklas-englert** [comment]
I have done thorough use tests now. I cannot find any issues related to the sound/mute behavior.  

It is possible that I don't understand your description of the issue correctly.

How exactly is the problem related to the new "auto unmute" feature? Does that issue appear to you in Chrome as well or are you not having my plugin installed there?

Could you please describe the problem in detail. What you want the site and plugin to do, and what it does instead. 


FYI:  
"auto unmute" was a quality-of-life feature request (see #7) to not always have to click on the centered video to unmute it.  
If you uncheck the "auto unmute" option, videos that were unmuted by this feature (and not by a click) will be muted again (as all introduced changes by this option are rolled back again; this also applies live to other tabs as well btw.).  
This re-muting of a video if you uncheck the auto-unmute is intentional (minus times minus are plus if you will).

**Comment by Paramirage** [comment]
I am also in favor of this auto-mute feature. I am not sure which feature but the addon is causing it. for example in firefox turn on 9gag control addon and go to this 9gag link : https://9gag.com/gag/a8qP2g1 

Just so you know, it is surprising happening to selected videos in 9gag and most of the videos are not affected. Just go to the video I mentioned in this comment and in the post to check if the addon caused the no-sound issue or not. When I turn off the addon, the sound comes back for both videos. Also to mention the problem is only happening in Firefox 123.0 which is the latest.

**Comment by Paramirage** [comment]
Also to mention the problem is only happening in Firefox 123.0 .
